"""
sds_types.py - Auto-generated from schema.sds

DO NOT EDIT - This file is generated by sds-codegen
Schema version: 1.0.0

Usage:
    from sds_types import SensorData

    table = node.register_table("SensorData", Role.DEVICE, schema=SensorData)
    table.state.temperature = 23.5
"""

from dataclasses import dataclass
from sds import Field

SCHEMA_VERSION = "1.0.0"

# ============== SensorData ==============


@dataclass
class SensorDataConfig:
    """Config section of SensorData table."""
    command: int = Field(uint8=True, default=0)
    threshold: float = Field(float32=True, default=25.0)

@dataclass
class SensorDataState:
    """State section of SensorData table."""
    temperature: float = Field(float32=True, default=0.0)
    humidity: float = Field(float32=True, default=0.0)

@dataclass
class SensorDataStatus:
    """Status section of SensorData table."""
    error_code: int = Field(uint8=True, default=0)
    battery_percent: int = Field(uint8=True, default=0)
    uptime_seconds: int = Field(uint32=True, default=0)

class SensorData:
    """
    Schema bundle for SensorData table.
    
    Usage:
        table = node.register_table("SensorData", Role.DEVICE, schema=SensorData)
    """
    Config = SensorDataConfig
    State = SensorDataState
    Status = SensorDataStatus


# ============== ActuatorData ==============


@dataclass
class ActuatorDataConfig:
    """Config section of ActuatorData table."""
    target_position: int = Field(uint8=True, default=0)
    speed: int = Field(uint8=True, default=50)

@dataclass
class ActuatorDataState:
    """State section of ActuatorData table."""
    current_position: int = Field(uint8=True, default=0)

@dataclass
class ActuatorDataStatus:
    """Status section of ActuatorData table."""
    motor_status: int = Field(uint8=True, default=0)
    error_code: int = Field(uint16=True, default=0)

class ActuatorData:
    """
    Schema bundle for ActuatorData table.
    
    Usage:
        table = node.register_table("ActuatorData", Role.DEVICE, schema=ActuatorData)
    """
    Config = ActuatorDataConfig
    State = ActuatorDataState
    Status = ActuatorDataStatus


# All exported types
__all__ = ['SensorData', 'ActuatorData', 'SCHEMA_VERSION']