/*
 * sds.h - SDS Core API Header
 * 
 * Simple DDS (SDS) - A simplified hub-and-spoke state synchronization library.
 * 
 * Usage:
 *   #include "sds.h"
 *   #include "sds_types.h"  // Generated from your schema.sds
 */

#ifndef SDS_H
#define SDS_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include "sds_error.h"
#include "sds_json.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ============== Configuration Constants ============== */

#define SDS_MAX_TABLES           8      /* Max tables per node */
#define SDS_MAX_NODE_ID_LEN      32     /* Max node ID string length */
#define SDS_MAX_TABLE_TYPE_LEN   32     /* Max table type name length */
#define SDS_DEFAULT_MQTT_PORT    1883
#define SDS_DEFAULT_SYNC_INTERVAL_MS 1000
#define SDS_TOPIC_BUFFER_SIZE    128
#define SDS_MSG_BUFFER_SIZE      512

/* ============== Core Types ============== */

/**
 * Role of a node for a particular table.
 */
typedef enum {
    SDS_ROLE_OWNER,     /* Can write config, receives state/status from devices */
    SDS_ROLE_DEVICE     /* Receives config, publishes state/status */
} SdsRole;

/**
 * Configuration for SDS initialization.
 */
typedef struct {
    const char* node_id;        /* Unique node identifier (NULL = auto-generate) */
    const char* mqtt_broker;    /* MQTT broker hostname/IP */
    uint16_t mqtt_port;         /* MQTT port (default 1883) */
} SdsConfig;

/**
 * Options for table registration.
 */
typedef struct {
    uint32_t sync_interval_ms;  /* Sync frequency (default 1000ms) */
} SdsTableOptions;

/**
 * Runtime statistics.
 */
typedef struct {
    uint32_t messages_sent;
    uint32_t messages_received;
    uint32_t reconnect_count;
    uint32_t errors;
} SdsStats;

/* ============== Callback Types ============== */

/**
 * Called when config is updated (device receives from owner).
 */
typedef void (*SdsConfigCallback)(const char* table_type);

/**
 * Called when state is updated (owner receives merged state).
 */
typedef void (*SdsStateCallback)(const char* table_type, const char* from_node);

/**
 * Called when status is updated (owner receives device status).
 */
typedef void (*SdsStatusCallback)(const char* table_type, const char* from_node);

/**
 * Iterator callback for sds_foreach_node.
 */
typedef void (*SdsNodeIterator)(const char* node_id, const void* status, void* user_data);

/**
 * Called when an error occurs during async operations (e.g., in sds_loop()).
 */
typedef void (*SdsErrorCallback)(SdsError error, const char* context);

/* ============== Serialization Types ============== */

/**
 * Function to serialize a section to JSON.
 */
typedef void (*SdsSerializeFunc)(void* section, SdsJsonWriter* w);

/**
 * Function to deserialize a section from JSON.
 */
typedef void (*SdsDeserializeFunc)(void* section, SdsJsonReader* r);

/* ============== Table Metadata (for registry-based registration) ============== */

/**
 * Complete metadata for a table type.
 * 
 * This structure is generated by codegen and contains all information
 * needed to register a table without explicit callbacks.
 * 
 * The SDS_TABLE_REGISTRY array in sds_types.h contains one entry per
 * table type defined in the schema.
 */
typedef struct {
    const char* table_type;             /* Table type name (e.g., "SensorNode") */
    uint32_t sync_interval_ms;          /* Default sync interval */
    
    /* Struct sizes */
    size_t device_table_size;           /* sizeof({Table}Table) */
    size_t owner_table_size;            /* sizeof({Table}OwnerTable) */
    
    /* Section offsets and sizes for DEVICE role */
    size_t dev_config_offset;
    size_t dev_config_size;
    size_t dev_state_offset;
    size_t dev_state_size;
    size_t dev_status_offset;
    size_t dev_status_size;
    
    /* Section offsets and sizes for OWNER role */
    size_t own_config_offset;
    size_t own_config_size;
    size_t own_state_offset;
    size_t own_state_size;
    
    /* Owner status slot management (for per-device tracking) */
    size_t own_status_slots_offset;     /* offsetof(OwnerTable, status_slots) */
    size_t own_status_slot_size;        /* sizeof(StatusSlot) */
    size_t own_status_count_offset;     /* offsetof(OwnerTable, status_count) */
    size_t slot_status_offset;          /* offsetof(StatusSlot, status) */
    uint8_t own_max_status_slots;       /* SDS_GENERATED_MAX_NODES */
    
    /* Serialization callbacks */
    SdsSerializeFunc serialize_config;
    SdsSerializeFunc serialize_state;
    SdsSerializeFunc serialize_status;
    
    /* Deserialization callbacks */
    SdsDeserializeFunc deserialize_config;
    SdsDeserializeFunc deserialize_state;
    SdsDeserializeFunc deserialize_status;
} SdsTableMeta;

/**
 * Look up table metadata by type name.
 * 
 * This function searches the registered table metadata for a matching entry.
 * 
 * @param table_type Name of table type to find
 * @return Pointer to metadata, or NULL if not found
 */
const SdsTableMeta* sds_find_table_meta(const char* table_type);

/**
 * Set the table registry (called once, typically from generated code).
 * 
 * @param registry Array of table metadata
 * @param count Number of entries in the array
 */
void sds_set_table_registry(const SdsTableMeta* registry, size_t count);

/* ============== Initialization API ============== */

/**
 * Initialize SDS and connect to MQTT broker.
 * 
 * @param config Configuration parameters
 * @return SDS_OK on success, error code otherwise
 */
SdsError sds_init(const SdsConfig* config);

/**
 * Process SDS events. Call this regularly (every loop iteration).
 */
void sds_loop(void);

/**
 * Shutdown SDS and disconnect from broker.
 */
void sds_shutdown(void);

/**
 * Check if SDS is initialized and connected.
 * 
 * @return true if ready to send/receive
 */
bool sds_is_ready(void);

/**
 * Get the node ID (auto-generated or from config).
 * 
 * @return Node ID string
 */
const char* sds_get_node_id(void);

/**
 * Get runtime statistics.
 * 
 * @return Pointer to stats structure
 */
const SdsStats* sds_get_stats(void);

/* ============== Table Registration API ============== */

/**
 * Register a table using the metadata registry.
 * 
 * This is the simple, user-friendly registration API. It looks up the table
 * type in the generated metadata registry and automatically provides all
 * serialization callbacks.
 * 
 * Usage:
 *   SensorNodeTable sensor_table = {0};
 *   sds_register_table(&sensor_table, "SensorNode", SDS_ROLE_DEVICE, NULL);
 * 
 * @param table Pointer to table structure
 * @param table_type Name of table type (must match schema)
 * @param role SDS_ROLE_OWNER or SDS_ROLE_DEVICE
 * @param options Optional parameters (NULL for defaults)
 * @return SDS_OK on success, error code otherwise
 */
SdsError sds_register_table(
    void* table,
    const char* table_type,
    SdsRole role,
    const SdsTableOptions* options
);

/**
 * Register a table with explicit serialization callbacks.
 * 
 * This is the extended registration that provides automatic serialization.
 * The generated helper functions (sds_register_{table}_device/owner) call this.
 * 
 * @param table Pointer to table structure
 * @param table_type Name of table type (must match schema)
 * @param role SDS_ROLE_OWNER or SDS_ROLE_DEVICE
 * @param options Optional parameters (NULL for defaults)
 * @param config_offset Offset of config section in table struct
 * @param config_size Size of config section
 * @param state_offset Offset of state section in table struct
 * @param state_size Size of state section
 * @param status_offset Offset of status section in table struct
 * @param status_size Size of status section
 * @param serialize_config Function to serialize config (owner only)
 * @param deserialize_config Function to deserialize config (device only)
 * @param serialize_state Function to serialize state
 * @param deserialize_state Function to deserialize state (owner only)
 * @param serialize_status Function to serialize status (device only)
 * @param deserialize_status Function to deserialize status (owner only)
 * @return SDS_OK on success, error code otherwise
 */
SdsError sds_register_table_ex(
    void* table,
    const char* table_type,
    SdsRole role,
    const SdsTableOptions* options,
    size_t config_offset, size_t config_size,
    size_t state_offset, size_t state_size,
    size_t status_offset, size_t status_size,
    SdsSerializeFunc serialize_config,
    SdsDeserializeFunc deserialize_config,
    SdsSerializeFunc serialize_state,
    SdsDeserializeFunc deserialize_state,
    SdsSerializeFunc serialize_status,
    SdsDeserializeFunc deserialize_status
);

/**
 * Unregister a table.
 * 
 * @param table_type Name of table type to unregister
 * @return SDS_OK on success, error code otherwise
 */
SdsError sds_unregister_table(const char* table_type);

/**
 * Get the number of registered tables.
 * 
 * @return Number of active tables
 */
uint8_t sds_get_table_count(void);

/* ============== Callback Registration ============== */

/**
 * Set callback for config updates.
 * 
 * @param table_type Table type to monitor
 * @param callback Function to call on config change
 */
void sds_on_config_update(const char* table_type, SdsConfigCallback callback);

/**
 * Set callback for state updates (owner only).
 * 
 * @param table_type Table type to monitor
 * @param callback Function to call on state change
 */
void sds_on_state_update(const char* table_type, SdsStateCallback callback);

/**
 * Set callback for status updates (owner only).
 * 
 * @param table_type Table type to monitor
 * @param callback Function to call on status change
 */
void sds_on_status_update(const char* table_type, SdsStatusCallback callback);

/**
 * Set callback for async error notifications.
 * 
 * Errors that occur during sds_loop() or other async operations
 * will be reported through this callback.
 * 
 * @param callback Function to call on error (NULL to disable)
 */
void sds_on_error(SdsErrorCallback callback);

/* ============== Owner Helpers ============== */

/**
 * Find status for a specific node (owner only).
 * 
 * @param owner_table Pointer to owner table structure
 * @param table_type Table type name
 * @param node_id Node ID to find
 * @return Pointer to status, or NULL if not found
 */
const void* sds_find_node_status(
    const void* owner_table,
    const char* table_type,
    const char* node_id
);

/**
 * Iterate over all known nodes (owner only).
 * 
 * @param owner_table Pointer to owner table structure
 * @param table_type Table type name
 * @param callback Function to call for each node
 * @param user_data User-provided context
 */
void sds_foreach_node(
    const void* owner_table,
    const char* table_type,
    SdsNodeIterator callback,
    void* user_data
);

/**
 * Configure status slot metadata for owner tables (for manual registration).
 * 
 * When using sds_register_table_ex() directly (not via codegen registry),
 * call this to enable per-device status tracking for owner tables.
 * 
 * @param table_type Table type name
 * @param slots_offset offsetof(OwnerTable, status_slots)
 * @param slot_size sizeof(StatusSlot)
 * @param slot_status_offset offsetof(StatusSlot, status)
 * @param count_offset offsetof(OwnerTable, status_count)
 * @param max_slots Maximum number of device slots
 */
void sds_set_owner_status_slots(
    const char* table_type,
    size_t slots_offset,
    size_t slot_size,
    size_t slot_status_offset,
    size_t count_offset,
    uint8_t max_slots
);

#ifdef __cplusplus
}

/* ============== Arduino C++ Wrapper ============== */

/**
 * Arduino-style wrapper class for SDS.
 * 
 * Provides a simpler interface for Arduino/ESP sketches.
 */
class SDSClient {
public:
    bool begin(const char* node_id, const char* broker, uint16_t port = 1883) {
        SdsConfig config = {
            .node_id = node_id,
            .mqtt_broker = broker,
            .mqtt_port = port
        };
        return sds_init(&config) == SDS_OK;
    }
    
    void loop() { sds_loop(); }
    void end() { sds_shutdown(); }
    bool isReady() { return sds_is_ready(); }
    const char* getNodeId() { return sds_get_node_id(); }
    const SdsStats* getStats() { return sds_get_stats(); }
    
    static const char* errorString(SdsError err) {
        return sds_error_string(err);
    }
};

#endif /* __cplusplus */

#endif /* SDS_H */
