/*
 * sds_types.h - Auto-generated from schema.sds
 * 
 * DO NOT EDIT - This file is generated by sds-codegen
 * Schema version: 1.0.0
 */

#ifndef SDS_TYPES_H
#define SDS_TYPES_H

#define SDS_SCHEMA_VERSION "1.0.0"

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "sds.h"
#include "sds_json.h"

#define SDS_GENERATED_MAX_NODES 16

/* ============== Table: SensorNode ============== */

#define SDS_SENSOR_NODE_SYNC_INTERVAL_MS 1000

/* Config section (Owner → Devices) */
typedef struct {
    uint8_t command;
    float threshold;
} SensorNodeConfig;

/* State section (All → Owner, LWW) */
typedef struct {
    float temperature;
    float humidity;
} SensorNodeState;

/* Status section (Device → Owner) */
typedef struct {
    uint8_t error_code;
    uint8_t battery_percent;
    uint32_t uptime_seconds;
} SensorNodeStatus;

/* Device Table (for SDS_ROLE_DEVICE) */
typedef struct {
    SensorNodeConfig config;
    SensorNodeState state;
    SensorNodeStatus status;
} SensorNodeTable;

/* Status slot for per-device tracking at Owner */
typedef struct {
    char node_id[SDS_MAX_NODE_ID_LEN];
    bool valid;
    uint32_t last_seen_ms;
    SensorNodeStatus status;
} SensorNodeStatusSlot;

/* Owner Table (for SDS_ROLE_OWNER) */
typedef struct {
    SensorNodeConfig config;
    SensorNodeState state;  /* Merged from all devices */
    SensorNodeStatusSlot status_slots[SDS_GENERATED_MAX_NODES];
    uint8_t status_count;
} SensorNodeOwnerTable;

static void sensor_node_serialize_config(void* section, SdsJsonWriter* w) {
    SensorNodeConfig* cfg = (SensorNodeConfig*)section;
    sds_json_add_uint(w, "command", cfg->command);
    sds_json_add_float(w, "threshold", cfg->threshold);
}

static void sensor_node_serialize_state(void* section, SdsJsonWriter* w) {
    SensorNodeState* st = (SensorNodeState*)section;
    sds_json_add_float(w, "temperature", st->temperature);
    sds_json_add_float(w, "humidity", st->humidity);
}

static void sensor_node_serialize_status(void* section, SdsJsonWriter* w) {
    SensorNodeStatus* st = (SensorNodeStatus*)section;
    sds_json_add_uint(w, "error_code", st->error_code);
    sds_json_add_uint(w, "battery_percent", st->battery_percent);
    sds_json_add_uint(w, "uptime_seconds", st->uptime_seconds);
}

static void sensor_node_deserialize_config(void* section, SdsJsonReader* r) {
    SensorNodeConfig* cfg = (SensorNodeConfig*)section;
    sds_json_get_uint8_field(r, "command", &cfg->command);
    sds_json_get_float_field(r, "threshold", &cfg->threshold);
}

static void sensor_node_deserialize_state(void* section, SdsJsonReader* r) {
    SensorNodeState* st = (SensorNodeState*)section;
    sds_json_get_float_field(r, "temperature", &st->temperature);
    sds_json_get_float_field(r, "humidity", &st->humidity);
}

static void sensor_node_deserialize_status(void* section, SdsJsonReader* r) {
    SensorNodeStatus* st = (SensorNodeStatus*)section;
    sds_json_get_uint8_field(r, "error_code", &st->error_code);
    sds_json_get_uint8_field(r, "battery_percent", &st->battery_percent);
    { uint32_t tmp; if (sds_json_get_uint_field(r, "uptime_seconds", &tmp)) st->uptime_seconds = tmp; }
}

/* ============== Table: ActuatorNode ============== */

#define SDS_ACTUATOR_NODE_SYNC_INTERVAL_MS 100

/* Config section (Owner → Devices) */
typedef struct {
    uint8_t target_position;
    uint8_t speed;
} ActuatorNodeConfig;

/* State section (All → Owner, LWW) */
typedef struct {
    uint8_t current_position;
} ActuatorNodeState;

/* Status section (Device → Owner) */
typedef struct {
    uint8_t motor_status;
    uint16_t error_code;
} ActuatorNodeStatus;

/* Device Table (for SDS_ROLE_DEVICE) */
typedef struct {
    ActuatorNodeConfig config;
    ActuatorNodeState state;
    ActuatorNodeStatus status;
} ActuatorNodeTable;

/* Status slot for per-device tracking at Owner */
typedef struct {
    char node_id[SDS_MAX_NODE_ID_LEN];
    bool valid;
    uint32_t last_seen_ms;
    ActuatorNodeStatus status;
} ActuatorNodeStatusSlot;

/* Owner Table (for SDS_ROLE_OWNER) */
typedef struct {
    ActuatorNodeConfig config;
    ActuatorNodeState state;  /* Merged from all devices */
    ActuatorNodeStatusSlot status_slots[SDS_GENERATED_MAX_NODES];
    uint8_t status_count;
} ActuatorNodeOwnerTable;

static void actuator_node_serialize_config(void* section, SdsJsonWriter* w) {
    ActuatorNodeConfig* cfg = (ActuatorNodeConfig*)section;
    sds_json_add_uint(w, "target_position", cfg->target_position);
    sds_json_add_uint(w, "speed", cfg->speed);
}

static void actuator_node_serialize_state(void* section, SdsJsonWriter* w) {
    ActuatorNodeState* st = (ActuatorNodeState*)section;
    sds_json_add_uint(w, "current_position", st->current_position);
}

static void actuator_node_serialize_status(void* section, SdsJsonWriter* w) {
    ActuatorNodeStatus* st = (ActuatorNodeStatus*)section;
    sds_json_add_uint(w, "motor_status", st->motor_status);
    sds_json_add_uint(w, "error_code", st->error_code);
}

static void actuator_node_deserialize_config(void* section, SdsJsonReader* r) {
    ActuatorNodeConfig* cfg = (ActuatorNodeConfig*)section;
    sds_json_get_uint8_field(r, "target_position", &cfg->target_position);
    sds_json_get_uint8_field(r, "speed", &cfg->speed);
}

static void actuator_node_deserialize_state(void* section, SdsJsonReader* r) {
    ActuatorNodeState* st = (ActuatorNodeState*)section;
    sds_json_get_uint8_field(r, "current_position", &st->current_position);
}

static void actuator_node_deserialize_status(void* section, SdsJsonReader* r) {
    ActuatorNodeStatus* st = (ActuatorNodeStatus*)section;
    sds_json_get_uint8_field(r, "motor_status", &st->motor_status);
    { uint32_t tmp; if (sds_json_get_uint_field(r, "error_code", &tmp)) st->error_code = tmp; }
}

/* ============== Max Section Size (for shadow buffers) ============== */

/* Helper macros for compile-time max calculation */
#define _SDS_MAX2(a, b) ((a) > (b) ? (a) : (b))
#define _SDS_MAX3(a, b, c) _SDS_MAX2(_SDS_MAX2(a, b), c)

/* Auto-calculated maximum section size across all tables */
#define SDS_GENERATED_MAX_SECTION_SIZE ( \
    _SDS_MAX2(_SDS_MAX3(_SDS_MAX3(sizeof(SensorNodeConfig), sizeof(SensorNodeState), sizeof(SensorNodeStatus)), sizeof(ActuatorNodeConfig), sizeof(ActuatorNodeState)), sizeof(ActuatorNodeStatus)) \
)

/* ============== Table Registry ============== */

#define SDS_TABLE_REGISTRY_COUNT 2

static const SdsTableMeta SDS_TABLE_REGISTRY[] = {
    /* SensorNode */
    {
        .table_type = "SensorNode",
        .sync_interval_ms = SDS_SENSOR_NODE_SYNC_INTERVAL_MS,
        .device_table_size = sizeof(SensorNodeTable),
        .owner_table_size = sizeof(SensorNodeOwnerTable),
        .dev_config_offset = offsetof(SensorNodeTable, config),
        .dev_config_size = sizeof(SensorNodeConfig),
        .dev_state_offset = offsetof(SensorNodeTable, state),
        .dev_state_size = sizeof(SensorNodeState),
        .dev_status_offset = offsetof(SensorNodeTable, status),
        .dev_status_size = sizeof(SensorNodeStatus),
        .own_config_offset = offsetof(SensorNodeOwnerTable, config),
        .own_config_size = sizeof(SensorNodeConfig),
        .own_state_offset = offsetof(SensorNodeOwnerTable, state),
        .own_state_size = sizeof(SensorNodeState),
        .own_status_slots_offset = offsetof(SensorNodeOwnerTable, status_slots),
        .own_status_slot_size = sizeof(SensorNodeStatusSlot),
        .own_status_count_offset = offsetof(SensorNodeOwnerTable, status_count),
        .slot_status_offset = offsetof(SensorNodeStatusSlot, status),
        .own_max_status_slots = SDS_GENERATED_MAX_NODES,
        .serialize_config = sensor_node_serialize_config,
        .serialize_state = sensor_node_serialize_state,
        .serialize_status = sensor_node_serialize_status,
        .deserialize_config = sensor_node_deserialize_config,
        .deserialize_state = sensor_node_deserialize_state,
        .deserialize_status = sensor_node_deserialize_status,
    },
    /* ActuatorNode */
    {
        .table_type = "ActuatorNode",
        .sync_interval_ms = SDS_ACTUATOR_NODE_SYNC_INTERVAL_MS,
        .device_table_size = sizeof(ActuatorNodeTable),
        .owner_table_size = sizeof(ActuatorNodeOwnerTable),
        .dev_config_offset = offsetof(ActuatorNodeTable, config),
        .dev_config_size = sizeof(ActuatorNodeConfig),
        .dev_state_offset = offsetof(ActuatorNodeTable, state),
        .dev_state_size = sizeof(ActuatorNodeState),
        .dev_status_offset = offsetof(ActuatorNodeTable, status),
        .dev_status_size = sizeof(ActuatorNodeStatus),
        .own_config_offset = offsetof(ActuatorNodeOwnerTable, config),
        .own_config_size = sizeof(ActuatorNodeConfig),
        .own_state_offset = offsetof(ActuatorNodeOwnerTable, state),
        .own_state_size = sizeof(ActuatorNodeState),
        .own_status_slots_offset = offsetof(ActuatorNodeOwnerTable, status_slots),
        .own_status_slot_size = sizeof(ActuatorNodeStatusSlot),
        .own_status_count_offset = offsetof(ActuatorNodeOwnerTable, status_count),
        .slot_status_offset = offsetof(ActuatorNodeStatusSlot, status),
        .own_max_status_slots = SDS_GENERATED_MAX_NODES,
        .serialize_config = actuator_node_serialize_config,
        .serialize_state = actuator_node_serialize_state,
        .serialize_status = actuator_node_serialize_status,
        .deserialize_config = actuator_node_deserialize_config,
        .deserialize_state = actuator_node_deserialize_state,
        .deserialize_status = actuator_node_deserialize_status,
    },
};

/* Auto-register tables with SDS core (runs before main) */
#if defined(__GNUC__) || defined(__clang__)
__attribute__((constructor))
#endif
static void _sds_auto_register_types(void) {
    sds_set_table_registry(SDS_TABLE_REGISTRY, SDS_TABLE_REGISTRY_COUNT);
}

#endif /* SDS_TYPES_H */
