/*
 * sds_types.h - Auto-generated from schema.sds
 * 
 * DO NOT EDIT - This file is generated by sds-codegen
 * Schema version: 1.0.0
 */

#ifndef SDS_TYPES_H
#define SDS_TYPES_H

#define SDS_SCHEMA_VERSION "1.0.0"

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "sds.h"
#include "sds_json.h"

#define SDS_GENERATED_MAX_NODES 16

/* ============== Table: SensorData ============== */

#define SDS_SENSOR_DATA_SYNC_INTERVAL_MS 1000
#define SDS_SENSOR_DATA_LIVENESS_INTERVAL_MS 3000

/* Config section (Owner → Devices) */
typedef struct {
    uint8_t command;
    float threshold;
} SensorDataConfig;

/* State section (All → Owner, LWW) */
typedef struct {
    float temperature;
    float humidity;
} SensorDataState;

/* Status section (Device → Owner) */
typedef struct {
    uint8_t error_code;
    uint8_t battery_percent;
    uint32_t uptime_seconds;
} SensorDataStatus;

/* Device Table (for SDS_ROLE_DEVICE) */
typedef struct {
    SensorDataConfig config;
    SensorDataState state;
    SensorDataStatus status;
} SensorDataTable;

/* Status slot for per-device tracking at Owner */
typedef struct {
    char node_id[SDS_MAX_NODE_ID_LEN];
    bool valid;
    bool online;             /* false if LWT received or graceful disconnect */
    bool eviction_pending;   /* true if awaiting grace period after LWT */
    uint32_t last_seen_ms;   /* Timestamp of last received status */
    uint32_t eviction_deadline; /* When to evict if device doesn't return */
    SensorDataStatus status;
} SensorDataStatusSlot;

/* Owner Table (for SDS_ROLE_OWNER) */
typedef struct {
    SensorDataConfig config;
    SensorDataState state;  /* Merged from all devices */
    SensorDataStatusSlot status_slots[SDS_GENERATED_MAX_NODES];
    uint8_t status_count;
} SensorDataOwnerTable;

static void sensor_data_serialize_config(void* section, SdsJsonWriter* w) {
    SensorDataConfig* cfg = (SensorDataConfig*)section;
    sds_json_add_uint(w, "command", cfg->command);
    sds_json_add_float(w, "threshold", cfg->threshold);
}

static void sensor_data_serialize_state(void* section, SdsJsonWriter* w) {
    SensorDataState* st = (SensorDataState*)section;
    sds_json_add_float(w, "temperature", st->temperature);
    sds_json_add_float(w, "humidity", st->humidity);
}

static void sensor_data_serialize_status(void* section, SdsJsonWriter* w) {
    SensorDataStatus* st = (SensorDataStatus*)section;
    sds_json_add_uint(w, "error_code", st->error_code);
    sds_json_add_uint(w, "battery_percent", st->battery_percent);
    sds_json_add_uint(w, "uptime_seconds", st->uptime_seconds);
}

static void sensor_data_deserialize_config(void* section, SdsJsonReader* r) {
    SensorDataConfig* cfg = (SensorDataConfig*)section;
    sds_json_get_uint8_field(r, "command", &cfg->command);
    sds_json_get_float_field(r, "threshold", &cfg->threshold);
}

static void sensor_data_deserialize_state(void* section, SdsJsonReader* r) {
    SensorDataState* st = (SensorDataState*)section;
    sds_json_get_float_field(r, "temperature", &st->temperature);
    sds_json_get_float_field(r, "humidity", &st->humidity);
}

static void sensor_data_deserialize_status(void* section, SdsJsonReader* r) {
    SensorDataStatus* st = (SensorDataStatus*)section;
    sds_json_get_uint8_field(r, "error_code", &st->error_code);
    sds_json_get_uint8_field(r, "battery_percent", &st->battery_percent);
    { uint32_t tmp; if (sds_json_get_uint_field(r, "uptime_seconds", &tmp)) st->uptime_seconds = tmp; }
}

/* Config field descriptors for delta sync */
static const SdsFieldMeta SDS_SENSOR_DATA_CONFIG_FIELDS[] = {
    { "command", SDS_FIELD_UINT8, offsetof(SensorDataConfig, command), sizeof(((SensorDataConfig*)0)->command) },
    { "threshold", SDS_FIELD_FLOAT, offsetof(SensorDataConfig, threshold), sizeof(((SensorDataConfig*)0)->threshold) },
};
#define SDS_SENSOR_DATA_CONFIG_FIELD_COUNT 2

/* State field descriptors for delta sync */
static const SdsFieldMeta SDS_SENSOR_DATA_STATE_FIELDS[] = {
    { "temperature", SDS_FIELD_FLOAT, offsetof(SensorDataState, temperature), sizeof(((SensorDataState*)0)->temperature) },
    { "humidity", SDS_FIELD_FLOAT, offsetof(SensorDataState, humidity), sizeof(((SensorDataState*)0)->humidity) },
};
#define SDS_SENSOR_DATA_STATE_FIELD_COUNT 2

/* Status field descriptors for delta sync */
static const SdsFieldMeta SDS_SENSOR_DATA_STATUS_FIELDS[] = {
    { "error_code", SDS_FIELD_UINT8, offsetof(SensorDataStatus, error_code), sizeof(((SensorDataStatus*)0)->error_code) },
    { "battery_percent", SDS_FIELD_UINT8, offsetof(SensorDataStatus, battery_percent), sizeof(((SensorDataStatus*)0)->battery_percent) },
    { "uptime_seconds", SDS_FIELD_UINT32, offsetof(SensorDataStatus, uptime_seconds), sizeof(((SensorDataStatus*)0)->uptime_seconds) },
};
#define SDS_SENSOR_DATA_STATUS_FIELD_COUNT 3

/* ============== Table: ActuatorData ============== */

#define SDS_ACTUATOR_DATA_SYNC_INTERVAL_MS 100
#define SDS_ACTUATOR_DATA_LIVENESS_INTERVAL_MS 1500

/* Config section (Owner → Devices) */
typedef struct {
    uint8_t target_position;
    uint8_t speed;
} ActuatorDataConfig;

/* State section (All → Owner, LWW) */
typedef struct {
    uint8_t current_position;
} ActuatorDataState;

/* Status section (Device → Owner) */
typedef struct {
    uint8_t motor_status;
    uint16_t error_code;
} ActuatorDataStatus;

/* Device Table (for SDS_ROLE_DEVICE) */
typedef struct {
    ActuatorDataConfig config;
    ActuatorDataState state;
    ActuatorDataStatus status;
} ActuatorDataTable;

/* Status slot for per-device tracking at Owner */
typedef struct {
    char node_id[SDS_MAX_NODE_ID_LEN];
    bool valid;
    bool online;             /* false if LWT received or graceful disconnect */
    bool eviction_pending;   /* true if awaiting grace period after LWT */
    uint32_t last_seen_ms;   /* Timestamp of last received status */
    uint32_t eviction_deadline; /* When to evict if device doesn't return */
    ActuatorDataStatus status;
} ActuatorDataStatusSlot;

/* Owner Table (for SDS_ROLE_OWNER) */
typedef struct {
    ActuatorDataConfig config;
    ActuatorDataState state;  /* Merged from all devices */
    ActuatorDataStatusSlot status_slots[SDS_GENERATED_MAX_NODES];
    uint8_t status_count;
} ActuatorDataOwnerTable;

static void actuator_data_serialize_config(void* section, SdsJsonWriter* w) {
    ActuatorDataConfig* cfg = (ActuatorDataConfig*)section;
    sds_json_add_uint(w, "target_position", cfg->target_position);
    sds_json_add_uint(w, "speed", cfg->speed);
}

static void actuator_data_serialize_state(void* section, SdsJsonWriter* w) {
    ActuatorDataState* st = (ActuatorDataState*)section;
    sds_json_add_uint(w, "current_position", st->current_position);
}

static void actuator_data_serialize_status(void* section, SdsJsonWriter* w) {
    ActuatorDataStatus* st = (ActuatorDataStatus*)section;
    sds_json_add_uint(w, "motor_status", st->motor_status);
    sds_json_add_uint(w, "error_code", st->error_code);
}

static void actuator_data_deserialize_config(void* section, SdsJsonReader* r) {
    ActuatorDataConfig* cfg = (ActuatorDataConfig*)section;
    sds_json_get_uint8_field(r, "target_position", &cfg->target_position);
    sds_json_get_uint8_field(r, "speed", &cfg->speed);
}

static void actuator_data_deserialize_state(void* section, SdsJsonReader* r) {
    ActuatorDataState* st = (ActuatorDataState*)section;
    sds_json_get_uint8_field(r, "current_position", &st->current_position);
}

static void actuator_data_deserialize_status(void* section, SdsJsonReader* r) {
    ActuatorDataStatus* st = (ActuatorDataStatus*)section;
    sds_json_get_uint8_field(r, "motor_status", &st->motor_status);
    { uint32_t tmp; if (sds_json_get_uint_field(r, "error_code", &tmp)) st->error_code = tmp; }
}

/* Config field descriptors for delta sync */
static const SdsFieldMeta SDS_ACTUATOR_DATA_CONFIG_FIELDS[] = {
    { "target_position", SDS_FIELD_UINT8, offsetof(ActuatorDataConfig, target_position), sizeof(((ActuatorDataConfig*)0)->target_position) },
    { "speed", SDS_FIELD_UINT8, offsetof(ActuatorDataConfig, speed), sizeof(((ActuatorDataConfig*)0)->speed) },
};
#define SDS_ACTUATOR_DATA_CONFIG_FIELD_COUNT 2

/* State field descriptors for delta sync */
static const SdsFieldMeta SDS_ACTUATOR_DATA_STATE_FIELDS[] = {
    { "current_position", SDS_FIELD_UINT8, offsetof(ActuatorDataState, current_position), sizeof(((ActuatorDataState*)0)->current_position) },
};
#define SDS_ACTUATOR_DATA_STATE_FIELD_COUNT 1

/* Status field descriptors for delta sync */
static const SdsFieldMeta SDS_ACTUATOR_DATA_STATUS_FIELDS[] = {
    { "motor_status", SDS_FIELD_UINT8, offsetof(ActuatorDataStatus, motor_status), sizeof(((ActuatorDataStatus*)0)->motor_status) },
    { "error_code", SDS_FIELD_UINT16, offsetof(ActuatorDataStatus, error_code), sizeof(((ActuatorDataStatus*)0)->error_code) },
};
#define SDS_ACTUATOR_DATA_STATUS_FIELD_COUNT 2

/* ============== Max Section Size (for shadow buffers) ============== */

/* Helper macros for compile-time max calculation */
#define _SDS_MAX2(a, b) ((a) > (b) ? (a) : (b))
#define _SDS_MAX3(a, b, c) _SDS_MAX2(_SDS_MAX2(a, b), c)

/* Auto-calculated maximum section size across all tables */
#define SDS_GENERATED_MAX_SECTION_SIZE ( \
    _SDS_MAX2(_SDS_MAX3(_SDS_MAX3(sizeof(SensorDataConfig), sizeof(SensorDataState), sizeof(SensorDataStatus)), sizeof(ActuatorDataConfig), sizeof(ActuatorDataState)), sizeof(ActuatorDataStatus)) \
)

/* ============== Table Registry ============== */

#define SDS_TABLE_REGISTRY_COUNT 2

static const SdsTableMeta SDS_TABLE_REGISTRY[] = {
    /* SensorData */
    {
        .table_type = "SensorData",
        .sync_interval_ms = SDS_SENSOR_DATA_SYNC_INTERVAL_MS,
        .liveness_interval_ms = SDS_SENSOR_DATA_LIVENESS_INTERVAL_MS,
        .device_table_size = sizeof(SensorDataTable),
        .owner_table_size = sizeof(SensorDataOwnerTable),
        .dev_config_offset = offsetof(SensorDataTable, config),
        .dev_config_size = sizeof(SensorDataConfig),
        .dev_state_offset = offsetof(SensorDataTable, state),
        .dev_state_size = sizeof(SensorDataState),
        .dev_status_offset = offsetof(SensorDataTable, status),
        .dev_status_size = sizeof(SensorDataStatus),
        .own_config_offset = offsetof(SensorDataOwnerTable, config),
        .own_config_size = sizeof(SensorDataConfig),
        .own_state_offset = offsetof(SensorDataOwnerTable, state),
        .own_state_size = sizeof(SensorDataState),
        .own_status_slots_offset = offsetof(SensorDataOwnerTable, status_slots),
        .own_status_slot_size = sizeof(SensorDataStatusSlot),
        .own_status_count_offset = offsetof(SensorDataOwnerTable, status_count),
        .slot_valid_offset = offsetof(SensorDataStatusSlot, valid),
        .slot_online_offset = offsetof(SensorDataStatusSlot, online),
        .slot_eviction_pending_offset = offsetof(SensorDataStatusSlot, eviction_pending),
        .slot_last_seen_offset = offsetof(SensorDataStatusSlot, last_seen_ms),
        .slot_eviction_deadline_offset = offsetof(SensorDataStatusSlot, eviction_deadline),
        .slot_status_offset = offsetof(SensorDataStatusSlot, status),
        .own_max_status_slots = SDS_GENERATED_MAX_NODES,
        .serialize_config = sensor_data_serialize_config,
        .serialize_state = sensor_data_serialize_state,
        .serialize_status = sensor_data_serialize_status,
        .deserialize_config = sensor_data_deserialize_config,
        .deserialize_state = sensor_data_deserialize_state,
        .deserialize_status = sensor_data_deserialize_status,
        .config_fields = SDS_SENSOR_DATA_CONFIG_FIELDS,
        .config_field_count = SDS_SENSOR_DATA_CONFIG_FIELD_COUNT,
        .state_fields = SDS_SENSOR_DATA_STATE_FIELDS,
        .state_field_count = SDS_SENSOR_DATA_STATE_FIELD_COUNT,
        .status_fields = SDS_SENSOR_DATA_STATUS_FIELDS,
        .status_field_count = SDS_SENSOR_DATA_STATUS_FIELD_COUNT,
    },
    /* ActuatorData */
    {
        .table_type = "ActuatorData",
        .sync_interval_ms = SDS_ACTUATOR_DATA_SYNC_INTERVAL_MS,
        .liveness_interval_ms = SDS_ACTUATOR_DATA_LIVENESS_INTERVAL_MS,
        .device_table_size = sizeof(ActuatorDataTable),
        .owner_table_size = sizeof(ActuatorDataOwnerTable),
        .dev_config_offset = offsetof(ActuatorDataTable, config),
        .dev_config_size = sizeof(ActuatorDataConfig),
        .dev_state_offset = offsetof(ActuatorDataTable, state),
        .dev_state_size = sizeof(ActuatorDataState),
        .dev_status_offset = offsetof(ActuatorDataTable, status),
        .dev_status_size = sizeof(ActuatorDataStatus),
        .own_config_offset = offsetof(ActuatorDataOwnerTable, config),
        .own_config_size = sizeof(ActuatorDataConfig),
        .own_state_offset = offsetof(ActuatorDataOwnerTable, state),
        .own_state_size = sizeof(ActuatorDataState),
        .own_status_slots_offset = offsetof(ActuatorDataOwnerTable, status_slots),
        .own_status_slot_size = sizeof(ActuatorDataStatusSlot),
        .own_status_count_offset = offsetof(ActuatorDataOwnerTable, status_count),
        .slot_valid_offset = offsetof(ActuatorDataStatusSlot, valid),
        .slot_online_offset = offsetof(ActuatorDataStatusSlot, online),
        .slot_eviction_pending_offset = offsetof(ActuatorDataStatusSlot, eviction_pending),
        .slot_last_seen_offset = offsetof(ActuatorDataStatusSlot, last_seen_ms),
        .slot_eviction_deadline_offset = offsetof(ActuatorDataStatusSlot, eviction_deadline),
        .slot_status_offset = offsetof(ActuatorDataStatusSlot, status),
        .own_max_status_slots = SDS_GENERATED_MAX_NODES,
        .serialize_config = actuator_data_serialize_config,
        .serialize_state = actuator_data_serialize_state,
        .serialize_status = actuator_data_serialize_status,
        .deserialize_config = actuator_data_deserialize_config,
        .deserialize_state = actuator_data_deserialize_state,
        .deserialize_status = actuator_data_deserialize_status,
        .config_fields = SDS_ACTUATOR_DATA_CONFIG_FIELDS,
        .config_field_count = SDS_ACTUATOR_DATA_CONFIG_FIELD_COUNT,
        .state_fields = SDS_ACTUATOR_DATA_STATE_FIELDS,
        .state_field_count = SDS_ACTUATOR_DATA_STATE_FIELD_COUNT,
        .status_fields = SDS_ACTUATOR_DATA_STATUS_FIELDS,
        .status_field_count = SDS_ACTUATOR_DATA_STATUS_FIELD_COUNT,
    },
};

/* Auto-register tables with SDS core (runs before main) */
#if defined(__GNUC__) || defined(__clang__)
__attribute__((constructor))
#endif
static void _sds_auto_register_types(void) {
    sds_set_table_registry(SDS_TABLE_REGISTRY, SDS_TABLE_REGISTRY_COUNT);
    sds_set_schema_version(SDS_SCHEMA_VERSION);
}

#endif /* SDS_TYPES_H */
